version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "📦 Instalando librerías..."
      - pip install pandas xgboost scikit-learn boto3 numpy requests

  pre_build:
    commands:
      - echo "📂 Usando Dataset incluido en el repositorio..."
      # Verificamos que el archivo exista (para debug)
      - ls -l training/raw_data/dataset_aire_zmcdmx.zip
      # Descomprimimos el archivo local hacia la carpeta temporal
      - unzip training/raw_data/dataset_aire_zmcdmx.zip -d /tmp/dataset_final

  build:
    commands:
      - echo "🧠 INICIANDO ENTRENAMIENTO GRAND SLAM (5 Contaminantes)..."
      - python training/train_v5_grand_slam.py

  post_build:
    commands:
      - echo "✅ Entrenamiento finalizado."
