version: 0.2

env:
  variables:
    ECR_REPO_NAME: "smability-telegram-core"
    LAMBDA_BOT_NAME: "Smability-Chatbot"
    LAMBDA_SCHEDULER_NAME: "Smability-Scheduler"
    AWS_REGION: "us-east-1"

phases:
  pre_build:
    commands: |
      echo "🤖 Iniciando Build UNIFICADO (Modo Bloque)..."
      echo "🆔 Obteniendo Account ID..."
      export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      
      echo "🔑 Logueando en ECR..."
      aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      IMAGE_TAG=latest

      echo "🔍 Verificando repo..."
      aws ecr describe-repositories --repository-names $ECR_REPO_NAME || aws ecr create-repository --repository-name $ECR_REPO_NAME

      echo "🔄 Sincronizando API Light..."
      cp api_light/lambda_function.py app/airegpt_telegram/lambda_api_light.py

  build:
    commands: |
      echo "📂 Entrando a carpeta del módulo..."
      cd app/airegpt_telegram
      
      echo "🧹 Limpiando Tag..."
      export CLEAN_TAG=${CODEBUILD_BUILD_ID##*:}
      echo "🏷️ Tag limpio: $CLEAN_TAG"
      
      echo "🐳 Construyendo Docker..."
      docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:build-$CLEAN_TAG

  post_build:
    commands: |
      export CLEAN_TAG=${CODEBUILD_BUILD_ID##*:}
      
      echo "⬆️ Subiendo a ECR..."
      docker push $REPOSITORY_URI:$IMAGE_TAG
      docker push $REPOSITORY_URI:build-$CLEAN_TAG
      
      echo "🔄 Actualizando Lambdas..."
      aws lambda update-function-code --function-name $LAMBDA_BOT_NAME --image-uri $REPOSITORY_URI:$IMAGE_TAG
      aws lambda update-function-code --function-name $LAMBDA_SCHEDULER_NAME --image-uri $REPOSITORY_URI:$IMAGE_TAG
      
      echo "✅ Despliegue completado."
